# GitHub Actions code
name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest
    - name: Run main.py
      run: |
        python main.py
      env:
        NAME: "Dennis"
    - name: Run greeting action
      uses: ./
      with:
        first_name: "GitHub"
        last_name: "Copilot"
